Add bookings
ilizian/java-shareit pull request #2
Opened 2023-06-25 22:51 UTC by ilizian

2023-06-27 06:39 UTC, alexache requested changes

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  @Data
В моделях JPA эта аннотация, а также @EqualsAndHashcode недопустимы, потому что сгенерированные методы не подходят для жизненного цикла модели

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +    @Query(value = "select b from Booking as b where b.booker.id =?1 and b.item.id = ?2 and b.status <> ?3 " +
Написано через @QUery, чтобы название метода было не слишком длинным? (Ответ да подходит, исправлять не нужно)

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoResponse.java
> +    private UserDto booker;
Лучше завести свои ДТО для этих сущностей в данном классе - не все поля этих ДТО актуальны для ДТО бронирования

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +@Data
Повторный комментарий для каждой модели

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/comment/dto/CommentDto.java
> +    private String authorName;
Можно бы побольше валидаций

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        User user = userStorage.getReferenceById(userId);
Почему не просто findById?

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemStorage.getReferenceById(itemId);
Зачем 2  раза получать пользователя и вещь? Почему бы не совместить в один вызов?

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(this::setBookingsForItem)
Это вызов метода с запросом в базу в цикле, так делать не стоит, лучше собирать список вещей, бронирований и их скрещивать друг с другом

2023-06-27 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      @NotBlank(message = "Неправильное описание")
Валидации в модели не нужны

2023-06-27 06:39 UTC, alexache commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Закомментированный код лучше удалять

2023-06-27 06:39 UTC, alexache commented on src/main/resources/schema.sql
> +    id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Java long соответствует BIGINT, а не Integer

2023-06-27 09:46 UTC, ilizian commented on src/main/java/ru/practicum/shareit/comment/dto/CommentDto.java
> +    private String authorName;
Изменил на @NotBlank и добавил валидацию @FutureOrPresent даты. Если в данной реализации поставить валидацию на authorName, то не получится оставить комментарий, т.к. на вход подаётся только текст

2023-06-27 09:59 UTC, ilizian commented on src/main/resources/schema.sql
> +    id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Исправил

2023-06-27 09:59 UTC, ilizian commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Исправил

2023-06-27 09:59 UTC, ilizian commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      @NotBlank(message = "Неправильное описание")
Исправил

2023-06-27 10:00 UTC, ilizian commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemStorage.getReferenceById(itemId);
Исправил

2023-06-27 10:00 UTC, ilizian commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        User user = userStorage.getReferenceById(userId);
Исправил

2023-06-27 10:00 UTC, ilizian commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +@Data
Исправил

2023-06-27 10:00 UTC, ilizian commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  @Data
Исправил

2023-06-27 10:27 UTC, ilizian commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoResponse.java
> +    private UserDto booker;
Исправил

2023-06-27 10:49 UTC, ilizian commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(this::setBookingsForItem)
Исправил

2023-06-27 11:03 UTC, ilizian commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +    @Query(value = "select b from Booking as b where b.booker.id =?1 and b.item.id = ?2 and b.status <> ?3 " +
Нет, он просто был неправильно написан... Исправил

2023-06-27 18:43 UTC, alexache requested changes

2023-06-27 18:43 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(this::setBookingsForItem)
Не вижу изменения: вызов метода setBookingForItem в stream().map() это и есть обращение к базе из цикла

2023-06-27 20:38 UTC, ilizian commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(this::setBookingsForItem)
> 

Извиняюсь, поторопился. Исправил

2023-06-28 19:21 UTC, alexache approved these changes

2023-06-28 20:02 UTC, merged