Add item requests
ilizian/java-shareit pull request #3
Opened 2023-06-30 12:08 UTC by ilizian

2023-07-01 05:43 UTC, ilizian commented
рано отправил :(

2023-07-02 10:01 UTC, alexache requested changes

2023-07-02 10:01 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                 @RequestBody ItemRequestDtoResponse itemRequestDtoResponse)
Немного странный тип данных для входного аргумента (Response), и хорошо бы добавить валидаций

2023-07-02 10:01 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        itemRequestStorage.save(itemRequest);
Лучше использовать результат выполнения в качестве возвращаемого значения из данного метода (и маппинга)

2023-07-02 10:01 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::setItems)
Это вызов метода, в котором есть обращение к базе данных, в цикле

2023-07-02 10:01 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::setItems)
И здесь запрос к базе в цикле

2023-07-02 10:01 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.id", is(bookingDtoResponse.getId()), Long.class));
Хорошо бы еще в таких тестовых методах добавить verify, чтобы убедиться что сервис вызывается ожидаемое количество раз

2023-07-02 10:01 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +@WebMvcTest(BookingMapper.class)
Зачем эта аннотация?

2023-07-02 10:01 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    List<User> users = new ArrayList<>();
Пропущен модификатор доступа у поля

2023-07-02 16:14 UTC, ilizian commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +@WebMvcTest(BookingMapper.class)
Да, здесь и в других MapperTest она лишняя. Убрал

2023-07-02 16:15 UTC, ilizian commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.id", is(bookingDtoResponse.getId()), Long.class));
Добавил

2023-07-02 16:16 UTC, ilizian commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    List<User> users = new ArrayList<>();
Добавил

2023-07-02 16:16 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        itemRequestStorage.save(itemRequest);
Исправил

2023-07-02 16:17 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                 @RequestBody ItemRequestDtoResponse itemRequestDtoResponse)
Исправил на ItemRequestDto и в последующих методах

2023-07-02 19:27 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::setItems)
Исправил

2023-07-02 19:27 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::setItems)
Исправил

2023-07-03 07:52 UTC, alexache approved these changes

2023-07-03 07:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        List<Item> items = itemStorage.findItemsByRequestNotNull();
Почему бы не использовать айди запросов, чтобы не выгружать все-все вещи с запросами?

2023-07-03 07:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                List<ItemDto> itemsReq = items.stream().filter(item -> item.getRequest().getId()
Много раз полностью обходить список не очень опитмально, лучше сначала сделать мапу одним проходом по списку, где будет айди запроса на список вещей

2023-07-03 07:52 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +public class ItemServiceTest {
Не очень понятный тест класс. Нужен @DataJpaTest и тест непосредственно на класс репозитория, а не добавление через сервис с ручным query, как же это проверить метод поиска?

2023-07-03 18:35 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        List<Item> items = itemStorage.findItemsByRequestNotNull();
На самом деле у меня возникла проблема с передачей списка id

2023-07-03 18:36 UTC, ilizian commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +public class ItemServiceTest {
Исправил

2023-07-03 18:36 UTC, ilizian commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                List<ItemDto> itemsReq = items.stream().filter(item -> item.getRequest().getId()
Исправил

2023-07-03 18:36 UTC, merged